spring.application.name=apigateway

server.port=8080

spring.cloud.gateway.server.webmvc.routes[0].id=serviciousuarios
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/usuarios/**

jwt.secret=c21hcnRsb2dpeGNhdHJpbmFmZXJuYW5kYWFuYWlzMTI=
jwt.expiration=86400000